Images load without Js
MovingBlocks/legacy-website pull request #120
Opened 2019-03-11 16:13 UTC by Vishwaak

Issue Id: #188

Problem: The Images were not displayed with Javascript disabled on the client browser.

How-to-check: Disable Javascript in your browser to see the image Load

2019-03-11 21:50 UTC, pollend requested changes

2019-03-11 21:50 UTC, pollend commented on index.html
> +              </<noscript>
you have an extra un-closed tag here.

2019-03-13 04:50 UTC, Vishwaak commented on index.html
> +              </<noscript>
It's been resolved.

2019-03-13 14:20 UTC, smsunarto requested changes

2019-03-13 14:20 UTC, smsunarto commented on index.html
> +              </<noscript>
This doesn't look right. Isn't it supposed to be `<noscript>`? and please indent the next line accordingly

2019-03-13 14:36 UTC, Vishwaak commented on index.html
> +              </<noscript>
Sorry about that. I guess this should resolve the issue.

2019-03-16 09:00 UTC, Vishwaak commented
All the changes are made. Hoping to get reviewed.

2019-03-16 22:03 UTC, merged

2019-03-16 22:04 UTC, Cervator commented
Looks good and is working now on https://terasology.org/ - thanks @Vishwaak ! :-)