Patron Added
MovingBlocks/legacy-website pull request #121
Opened 2019-03-17 18:45 UTC by Vishwaak

Issue Id: #114 
 Problem: The  navigation menu did not have a patron link 
How-to-check: Looking up on the navigation bar in desktop view also in mobile view.
--

2019-03-17 19:55 UTC, jellysnake commented
Lets preview this

2019-03-17 19:56 UTC, jellysnake commented
(testing out a bot thingie)
I'll actual look at this later

2019-03-20 07:26 UTC, smsunarto commented
Let's preview this

2019-03-20 07:26 UTC, gooey-splashsite commented
Preview is available on http://preview.terasology.net/splashsite/pull/121 :rocket:

2019-06-29 02:35 UTC, Cervator requested changes
Didn't spot this for a while. Not sure the preview is working - the preview for this PR is there still, but shows no sign of the Patreon link. Might just have to preview it locally.

However, I'm not sure why the alt text on an image is "You show know" - that isn't helpful.

2019-06-29 02:35 UTC, Cervator commented on _includes/nav.html
> +          <li class="red lighten-1"> <a href="https://www.patreon.com/Terasology"><img style="height:68%;;"class="img-margin   z-depth-3" src="{{ site.baseurl}}/img/patron.png" alt="You should know"<
Why is the alt "You should know" ? That's not really a descriptive alternative to an image.

2019-06-29 02:42 UTC, Vishwaak commented on _includes/nav.html
> +          <li class="red lighten-1"> <a href="https://www.patreon.com/Terasology"><img style="height:68%;;"class="img-margin   z-depth-3" src="{{ site.baseurl}}/img/patron.png" alt="You should know"<
Sorry my bad, it should have skidded in while debugging. Will get it corrected  by tonight.

2019-07-01 00:52 UTC, pollend commented on _includes/nav.html
> +          <li class="red lighten-1"> <a href="https://www.patreon.com/Terasology"><img style="height:68%;;"class="img-margin   z-depth-3" src="{{ site.baseurl}}/img/patron.png" alt="You should know"<
you have an extra spaces in your class name. you don't need the semicolon in the style tag.

2019-07-11 16:39 UTC, closed without merging