Added OS specific download page
MovingBlocks/legacy-website pull request #138
Opened 2020-03-17 20:35 UTC by meetcshah19

Created a Download page which autodetects OS and fetches the required package using github API.

TODO :

- "https://api.github.com/repos/MovingBlocks/TerasologyLauncher/releases/tags/v4.0.0-rc.2" is statically linked right now instead of latest as our current latest release (v3.3.0) doesn’t have bundled JRE , change it to releases/latest once the new version is released .

2020-03-18 07:40 UTC, sin3point14 requested changes

2020-03-18 07:40 UTC, sin3point14 commented on download.html
> +  </div>
The elements not being vertically aligned is a bit visually unappealing would be great if they all have there centres horizontally aligned.
![image](https://user-images.githubusercontent.com/43549821/76935114-846aa500-6916-11ea-8ecf-040703daf4a2.png)
"OR Download without JRE" row div should be shifted out of its parent row div. Then this might help with the alignment within columns- https://medium.com/wdstack/bootstrap-4-vertical-center-1211448a2eff 
I think that the secondary link should be centered instead of being just below the main download link, this seems a bit weird compared to what a user is used to seeing in download links on the internet.

2020-03-18 07:40 UTC, sin3point14 commented on js/OSdetect.js
> +    var s = "";
use `let` instead of `var`, reloading the page may mess this up and use a better variable name

2020-03-18 07:40 UTC, sin3point14 commented on js/OSdetect.js
> +function call() {
use a better function name like `download()`

2020-03-18 11:17 UTC, meetcshah19 commented
Done @sin3point14

2020-03-18 13:00 UTC, sin3point14 requested changes
In general, avoid inline CSS : )

2020-03-18 13:00 UTC, sin3point14 commented on download.html
> +    <select style="display: block;" id="OS">
don't use inline CSS! use this instead- https://v4-alpha.getbootstrap.com/utilities/display-property/

2020-03-18 13:00 UTC, sin3point14 commented on download.html
> +  <div class="col s6 l2 my-auto" style="display: flex;justify-content: center;">
no need to make this a flex for justification bootstrap provides simple classes for that. remove the inline CSS and add `center` to the classes

2020-03-18 13:00 UTC, sin3point14 commented on download.html
> +  <div class="col s6 l3" style="display: flex;justify-content: center;">
change this as well

2020-03-18 13:00 UTC, sin3point14 commented on download.html
> +  <div class="col s6 l3" style="display: flex;justify-content: center;">
change this as well

2020-03-18 13:00 UTC, sin3point14 commented on js/OSdetect.js
> +    let s = "";
replace `s` by some meaningful name

2020-03-18 15:00 UTC, sin3point14 approved these changes
LGTM

2020-03-18 17:07 UTC, skaldarnar requested changes

2020-03-18 17:07 UTC, skaldarnar commented on download.html
> +      <option>macOs (32-Bit)</option>
This does not exist.
```suggestion
```

2020-03-18 17:07 UTC, skaldarnar commented on download.html
> +      <option>macOs (64-Bit)</option>
MacOS is only 64-bit.

```suggestion
      <option>MacOS</option>
```

2020-03-18 17:07 UTC, skaldarnar commented on js/OSdetect.js
> +        case 0:
This links the indices of the options implicitly with the download 👀 I would rather do it by name, such that we can be sure to download the right package.
It is very easy to miss this connection later on, and things would break when re-arranging the options.

2020-03-18 17:10 UTC, jdrueckert requested changes

2020-03-18 17:10 UTC, jdrueckert commented on _includes/nav.html
> +            src="{{ "/img/logo.png" | prepend: site.baseurl }}"></a>
```suggestion
        <a aria-label="Terasology Logo" class="brand-logo" href="{{ site.baseurl }}/">
            <img alt="Terasology" src="{{ "/img/logo.png" | prepend: site.baseurl }}">
        </a>
```

2020-03-18 17:10 UTC, jdrueckert commented on _includes/nav.html
> +            class="material-icons">menu</i></a>
```suggestion
        <a aria-label="Menu" href="#" data-activates="mobile-demo" class="button-collapse">
            <i class="material-icons">menu</i>
        </a>
```

2020-03-18 17:10 UTC, jdrueckert commented on _includes/nav.html
> +              </a></li>
```suggestion
          <li class="green darken-2">
              <a aria-label="Download Terasology" href="{{ "/download.html" | prepend: baseurl }}">
                  <i class="material-icons left">cloud_download</i>
                  Download
              </a>
          </li>
```

2020-03-18 17:10 UTC, jdrueckert commented on _includes/nav.html
> +              href="{{ "/download.html" | prepend: site.baseurl }}"><i class="material-icons left">cloud_download</i>Download</a></li>
```suggestion
    <li class="grey lighten-2">
        <a aria-label="Download Terasology" href="{{ "/download.html" | prepend: site.baseurl }}">
            <i class="material-icons left">cloud_download</i>
            Download
        </a>
    </li>
```

2020-03-18 17:10 UTC, jdrueckert commented on _includes/nav.html
> +<!-- Stop ignoring HTMLLintBear -->
please add a newline to the end of the file

2020-03-18 17:10 UTC, jdrueckert commented on download.html
> +</div>
see above

2020-03-18 17:10 UTC, jdrueckert commented on js/OSdetect.js
> +
please remove unnecessary empty lines (but keep a newline at the end of the file)

2020-03-20 20:51 UTC, jdrueckert requested changes

2020-03-20 20:51 UTC, jdrueckert commented on download.html
> +      <option>MacOs</option>
Please use the correct spelling "macOS" (https://de.wikipedia.org/wiki/MacOS).
```suggestion
      <option>macOS</option>
```

2020-03-20 20:51 UTC, jdrueckert commented on js/OSdetect.js
> +
```suggestion
```

2020-03-20 20:51 UTC, jdrueckert commented on js/OSdetect.js
> +    selectElement("MacOs");
```suggestion
    selectElement("macOS");
```

2020-03-20 20:51 UTC, jdrueckert commented on js/OSdetect.js
> +        case "MacOs":
```suggestion
        case "macOS":
```

2020-03-20 20:56 UTC, jdrueckert approved these changes
Looks good to me 👍

2020-03-20 20:58 UTC, skaldarnar approved these changes

2020-03-20 21:00 UTC, merged