Added Mentors Page with Trello as a backend
MovingBlocks/legacy-website pull request #144
Opened 2020-05-10 12:11 UTC by TheShubham99

Board Link - 
https://trello.com/b/wdOVNQgo/mentors

2020-05-10 16:07 UTC, pollend requested changes

2020-05-10 16:07 UTC, pollend commented on js/moment.js
> +//! moment.js
can you use this library from a CDN:
https://cdnjs.com/libraries/moment.js/

2020-05-10 17:23 UTC, TheShubham99 commented on js/moment.js
> +//! moment.js
Sure.

2020-05-11 07:38 UTC, TheShubham99 reviewed
@pollend `moment.js` included (`CDN version`) and `Gitpod Button` commit synced from the `master`.

2020-05-11 15:26 UTC, pollend commented
this looks pretty good. @Cervator is there anything else?

![image](https://user-images.githubusercontent.com/854359/81579518-216b1c80-9361-11ea-8891-2238bd0ee9cf.png)

2020-05-11 15:27 UTC, pollend approved these changes

2020-05-11 15:29 UTC, TheShubham99 commented
@pollend Thanks for reviewing :)

2020-05-11 15:40 UTC, Cervator approved these changes

2020-05-11 15:45 UTC, merged

2020-05-11 15:59 UTC, TheShubham99 commented
@pollend @Cervator Thanks for the review & merge. :)