post: TeraSaturday 5
MovingBlocks/legacy-website pull request #156
Opened 2020-11-19 23:02 UTC by skaldarnar

Extracted from #155 

Post comes with a new highlight video of FlowingLiquids on our youtube channel: https://youtu.be/CQHqrmoUWxQ

2020-11-19 23:28 UTC, Cervator approved these changes, later dismissed
Can't see the blog post via GitPod for some odd reason, but text-wise it seems good 👍

2020-11-19 23:28 UTC, Cervator commented on _posts/2020-11-21-terasaturday-5.md
> +<!--TODO: replace with screenshot of Metal Renegades robots-->
Completed todo?

2020-11-19 23:28 UTC, Cervator commented on _posts/2020-11-21-terasaturday-5.md
> +Finally, we also made the step towards [LW**JGL**](https://www.lwjgl.org/) thanks to the effort and contributions of _@DarkWeird_. This was initially suggested in December 2015 (now I'm feeling old .
Can't find a way to quickly preview, so is ` [LW**JGL**]` intentional with the asterisks? Does that bold "JGL" on purpose or  is it something accidental?

2020-11-20 08:51 UTC, skaldarnar commented on _posts/2020-11-21-terasaturday-5.md
> +Finally, we also made the step towards [LW**JGL**](https://www.lwjgl.org/) thanks to the effort and contributions of _@DarkWeird_. This was initially suggested in December 2015 (now I'm feeling old .
It's on purpose, and it actually works that way 🙃 [LWJGL](https://www.lwjgl.org/) stylize themselves this way on their website, that's why I've gone for it.

2020-11-20 08:52 UTC, skaldarnar commented on _posts/2020-11-21-terasaturday-5.md
> +<!--TODO: replace with screenshot of Metal Renegades robots-->
Yes, that's resolved.
```suggestion
```

2020-11-20 09:21 UTC, skaldarnar commented
Thanks for the review @Cervator 💚 

I've updated the PR description with instructions how to make it visible in gitpod. As the post is to be published in the future we need to provide the `--future` flag to `jekyll serve`.

2020-11-20 21:39 UTC, jdrueckert requested changes

2020-11-20 21:39 UTC, jdrueckert commented on _posts/2020-11-21-terasaturday-5.md
> +That's an average of >4 PRs merged each day! We'll try to sum up the major achievements below, but feel free to read through each an every commit message at your convenience 😋
```suggestion
That's an average of >4 PRs merged each day! We'll try to sum up the major achievements below, but feel free to read through each and every commit message at your convenience 😋
```

2020-11-20 21:39 UTC, jdrueckert commented on _posts/2020-11-21-terasaturday-5.md
> +_@immortius_ proposed to switch to [glTF](https://www.khronos.org/gltf/) for models and animations more than a year ago (see [MovingBlocks/Terasology#3785](https://github.com/MovingBlocks/Terasology/
```suggestion
_@immortius_ proposed to switch to [glTF](https://www.khronos.org/gltf/) for models and animations more than a year ago (see [MovingBlocks/Terasology#3785](https://github.com/MovingBlocks/Terasology/pull/3785)) and with the help of _@PAndaContron_, _@Qwertygiy_, and _@Michael P_ we eventually merged this to our main branch. Since then, _@Niruandaleth_ and _@casals_ have been working on the [glTF clean-up](https://github.com/MovingBlocks/Terasology/issues/4156), adjusting and fixing all the old MD5 models and animations in the game. We actually have so many of those that we should definitely make better use of them 🧐 (and we already have some ideas on how to do that ...).
```

2020-11-20 21:39 UTC, jdrueckert commented on _posts/2020-11-21-terasaturday-5.md
> +In a similar fashion, [MetalRenegades](https://github.com/Terasology/MetalRenegades) is now way more ... metal 🤘 We replaced some of the Gooey citizens with actual robot models. Representing the good
```suggestion
In a similar fashion, [MetalRenegades](https://github.com/Terasology/MetalRenegades) is now way more ... metal 🤘 We replaced some of the Gooey citizens with actual robot models. Representing the good and lawful, sheriff robots will help to keep the piece in the old west towns. Opposing, the bad robots with their bulky, barrell-like bodies bend the boundaries of decency. Which side do you chose?
```

2020-11-20 21:39 UTC, jdrueckert commented on _posts/2020-11-21-terasaturday-5.md
> +With the mass-preserving system of flowing liquids water becomes a valuable resources that should be used with care.
```suggestion
With the mass-preserving system of flowing liquids water becomes a valuable resource that should be used with care. 
```

2020-11-20 21:41 UTC, jdrueckert approved these changes

2020-11-20 21:44 UTC, merged